name: dart_raw
version: 0.2.0
homepage: https://github.com/mohn93/dart-raw
description: A package for writing, reading, and debugging binary data.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: '^1.0.0'
  fixnum: '^1.0.0'
  matcher: '>=0.9.0 <2.0.0'
  meta: '^1.15.0'

dev_dependencies:
  benchmark_harness: ^2.3.1
  test: ^1.0.0